### ISSUE TITLE
Remediate CVE's from Twistlock scan

### ISSUE THREAD

**Issue by cohsk** [cohsk/athena-log-cleaner#10]
Twistlock scan results are here --  https://jira.cohesity.com/browse/COSDN-3669

Note -- CVE's are not available publicly.  I do not want to advertise vulnerabilities.

**Comment by ankur4899** [comment]
The vulnerabilities are fixed :- 
Please refer this pull request and approve if you find it ok
https://github.com/cohsk/athena-log-cleaner/pull/11

**Comment by cohsk** [comment]
Looks good.  Changes have been merged.  New version has been submitted for scanning
